inherits = "catppuccin_mocha"

"ui.background" = ""

"ui.bufferline" = { fg = "subtext0", bg = "crust" }
"ui.bufferline.active" = { fg = "mauve", bg = "crust" }
"ui.bufferline.background" = { bg = "crust" }
